services:
  redis-master:
    image: redis-master
    build:
      dockerfile: Dockerfile.master
    networks:
    - redis-network
    ports:
    - "6391:6379"

  redis-slave:
    image: redis-slave
    build:
      dockerfile: Dockerfile.slave
    depends_on:
    - redis-master
    networks:
    - redis-network
    ports:
    - "6392:6379"

  redis-sentinel:
    image: redis-sentinel
    build:
      dockerfile: Dockerfile.sentinel
    depends_on:
    - redis-master
    networks:
    - redis-network
    deploy:
      replicas: 3

networks:
  redis-network:
