services:
  redis-master:
    image: redis-master
    build:
      dockerfile: Dockerfile.master
    networks:
    - redis-network
    ports:
    - "6391:6379"
    # # Uncomment the following for setting up SSL with certificates
    # volumes:
    # - /home/soham/tests/tls:/usr/local/etc/redis/certs

  redis-slave:
    image: redis-slave
    build:
      dockerfile: Dockerfile.slave
    depends_on:
    - redis-master
    networks:
    - redis-network
    ports:
    - "6392:6379"
    # volumes:
    # - /home/soham/tests/tls:/usr/local/etc/redis/certs

  redis-sentinel:
    image: redis-sentinel
    build:
      dockerfile: Dockerfile.sentinel
    depends_on:
    - redis-master
    networks:
    - redis-network
    deploy:
      replicas: 3
    ports:
    - "26379-26381:26379"
    # volumes:
    # - /home/soham/tests/tls:/usr/local/etc/sentinel/certs

networks:
  redis-network:
